# Generated by Django 4.2.7 on 2023-12-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_userquizhistory_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.RemoveField(
            model_name='response',
            name='selected_answer',
        ),
        migrations.AddField(
            model_name='response',
            name='selected_answer',
            field=models.ManyToManyField(to='quiz.choice'),
        ),
    ]
